### PR TITLE
SigTauRoster relations.js

### PR DESCRIPTION
**Pull request by SigTauDeltaPhi**
Updates Roster

### CODE REVIEW

**Comment by nfischer** [comment]
Hey there :wave: I'm excited to see you're working on a family tree for your fraternity! Let me know if you have any questions about getting this set up for your members. https://github.com/nfischer/framily-tree/wiki/Forking-instructions should cover most of the steps, but I'm happy to answer any questions.

**Comment by SigTauDeltaPhi** [comment]
Hey! Yah I was trying to take on the task of making our family line documented better. I am not a programmer by any means and this was my first experience with using GitHub to make a project. I think I brute forced your code to get it to "work" but I definitely know most other things like the spreadsheet are not linked probably lol

**Comment by nfischer** [comment]
Just took a look at your fork and the family tree site looks cool. Nicely done! Super impressive that you have fraternity history records going back to the 90's :+1:

**Comment by SigTauDeltaPhi** [comment]
Thank you very much! But I am having a few problems with the google sheet linking with the website, i got around it by just inputting the JSON code from the sheet directly into the relations.js file. How would you go about fixing this probelm?

**Pull request closed without merging**
